function qh_ann = choke_boundary_obs(Qvec_ann,L_eigv,choke_position,Kc,...
    area_ann,Cl,CTE,max_itr,tol,pchoke_plant,L3,rho0,p0)

qh_ann = newton_solver(@(qh_ann)choke_bc_obs(qh_ann,Qvec_ann,L_eigv,choke_position,Kc,area_ann,Cl,CTE,pchoke_plant,L3,rho0,p0),...
        @(qh_ann)choke_jacob_obs(qh_ann,Kc,choke_position,Cl,CTE,L_eigv,...
        area_ann,L3),Qvec_ann(:,end),max_itr,tol);

