function qh_ann = choke_boundary_obs1(Qvec_ann,L_eigv,choke_position,Kc,area_ann,Cl,...
    CTE,max_itr,tol,pchoke_plant,L3,rho0,p0,C1, C2, K_vu, K_vv, choke_position_ss)

qh_ann = newton_solver(@(qh_ann)choke_bc_obs1(qh_ann,Qvec_ann,L_eigv,choke_position,Kc,area_ann,...
    Cl,CTE,pchoke_plant,L3,rho0,p0, C1, C2, K_vu, K_vv, choke_position_ss),...
        @(qh_ann)choke_jacob_obs1(qh_ann,Kc,choke_position,Cl,CTE,L_eigv,...
        area_ann,L3, C1, C2, K_vu, K_vv, choke_position_ss),Qvec_ann(:,end),max_itr,tol);